# _config.yml
title:            Connor S. Kenaston
tagline:          'Scholar of U.S. History'
description:      'Social and cultural historian of the U.S. and the Atlantic World'
url:              https://connorskenaston.com
baseurl:          "" # root of the domain

# Other configurations
highlighter:      rouge
permalink:        pretty
plugins:          [jekyll-paginate]
paginate:         5
version:          2.1.0

github:
  repo:           https://github.com/ckenaston/ckenaston.github.io.git