# Dependencies
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Connor S. Kenaston
tagline:          'Scholar of U.S. History'
description:      'Historian of religion, politics, and culture in the United States'
url:              https://connorkenaston.com
baseurl:          /


paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/ckenaston/ckenaston.github.io.git
