# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Connor S. Kenaston
tagline:          'Scholar of U.S. History'
description:      'Social and cultural historian of the U.S. and the Atlantic World'
url:              https://ckenaston.github.io/
baseurl:          /

plugins:          [jekyll-paginate]
paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/ckenaston/ckenaston.github.io.git
