# _config.yml
title:            Connor S. Kenaston
tagline:          'Scholar of U.S. History and Culture'
description:      'Scholar of American History and Culture'
url:              https://connorskenaston.com
baseurl:          "" # root of the domain

# Other configurations
highlighter:      rouge
permalink:        pretty
plugins:          [jekyll-paginate]
paginate:         7
version:          2.1.0

github:
  repo:           https://github.com/ckenaston/ckenaston.github.io.git